### ISSUE TITLE
Issue with 'ExcludeProductList' parameter is missing a value

### ISSUE THREAD

**Issue by tju-pwsh** [jonasatgit/updatereporting#20]
I imported the reports. When I try to run anything with an exclude product lits by running in console I receive the following message:

Running ConfigMgr 2203 and SQL Server 2019 with SQL Reporting 15.0.1102.962

The 'ExcludeProductList' parameter is missing a value
![Report](https://user-images.githubusercontent.com/54526476/210800231-83be3745-f002-4418-a19d-d8973b467ac4.png)

Microsoft.Reporting.WinForms.MissingParameterException
The 'ExcludeProductList' parameter is missing a value

Stack Trace:
   at Microsoft.Reporting.WinForms.RSParams.ValidateReportInputsSatisfied()
   at Microsoft.Reporting.WinForms.RSParams.EnsureParamsLoaded(Boolean forceCredentialsShown, ReportParameterInfoCollection parameterInfos)
   at Microsoft.Reporting.WinForms.RSParams.EnsureParamsLoaded()
   at Microsoft.Reporting.WinForms.ReportViewer.RenderReportWithNewParameters(Int32 pageNumber, PostRenderArgs postRenderArgs)

-------------------------------

**Comment by jonasatgit** [comment]
Hi @tju-pwsh this happens if you don't sync Defender Pattern Updates in your environment. In that case choose "..nothing excluded" as parameter value. 

Hope the report helps
Jonas
